version: '2.2'
services:
  appscope01:
    image: "cribl/scope:${APPSCOPE_VERSION:-1.1.0}"
    container_name: appscope01
    environment:
      SCOPE_EVENT_METRIC: "true"
      SCOPE_EVENT_HTTP: "true"
      SCOPE_EVENT_NET: "true"
      SCOPE_EVENT_FS: "true"
      SCOPE_CRIBL: "${APPSCOPE_DEST:-tcp://cribl01:10090}"
      SCOPE_TAG_container_name: "appscope01"
      LD_PRELOAD: /usr/local/lib/libscope.so
    networks:
      - splunk_net

  appscope02:
    image: "cribl/scope:${APPSCOPE_VERSION:-1.1.0}"
    container_name: appscope02
    environment:
      SCOPE_EVENT_METRIC: "true"
      SCOPE_EVENT_HTTP: "true"
      SCOPE_EVENT_NET: "true"
      SCOPE_EVENT_FS: "true"
      SCOPE_CRIBL: "${APPSCOPE_DEST:-tcp://cribl01:10090}"
      SCOPE_TAG_container_name: "appscope02"
    tty: true
    networks:
      - splunk_net

  appscope01_tls:
    image: "cribl/scope:${APPSCOPE_VERSION:-1.1.0}"
    container_name: appscope01_tls
    environment:
      SCOPE_EVENT_METRIC: "true"
      SCOPE_EVENT_HTTP: "true"
      SCOPE_EVENT_NET: "true"
      SCOPE_EVENT_FS: "true"
      SCOPE_CRIBL: "${APPSCOPE_DEST_TLS:-tcp://cribl01:10091}"
      SCOPE_CRIBL_TLS_ENABLE: "true"
      SCOPE_CRIBL_TLS_CA_CERT_PATH: "${TLS_CA_CERT:-/opt/domain.crt}"
      SCOPE_TAG_container_name: "appscope01_tls"
    tty: true
    networks:
      - splunk_net

  redis:
    container_name: redis01
    image: redis:latest
    command: redis-server --appendonly yes
    networks:
      - splunk_net

  appscope_sshd:
    build:
      context: ./images
      dockerfile: Dockerfile
    container_name: appscope_sshd
    ports:
      - "2022:22"
    tty: true
    entrypoint:
      - ldscope
      - --
      - /usr/sbin/sshd
      - -D
    networks:
      - splunk_net
    # Debug
    cap_add:
      - SYS_PTRACE


  cribl01:
    image: "cribl/cribl:${CRIBL_VERSION:-3.4.2}"
    container_name: cribl01
    ports:
      - "${CRIBL_HOST_PORT:-9000}:9000"
    networks:
      - splunk_net

  splunk01:
    image: "splunk/splunk:${SPLUNK_VERSION:-8.2.6}"
    container_name: splunk01
    ports:
      - "${SPLUNK_HTTP_PORT:-8000}:${SPLUNK_HTTP_PORT:-8000}"
      - "${SPLUNK_ADMIN_PORT:-8089}:${SPLUNK_ADMIN_PORT:-8089}"
      - "${SPLUNK_S2S_PORT:-9997}:${SPLUNK_S2S_PORT:-9997}"
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "changed!"
    networks:
      - splunk_net
    volumes:
      - ./splunk/AppScopeSSHDDemo:/opt/splunk/etc/apps/AppScopeSSHDDemo

networks:
  splunk_net:
    driver: bridge
